const data = {
  products: [
    {
      name: 'free shirt',
      slug: 'free-shirt',
      category: 'shirts',
      image: '/images/shirt1.jpg',
      price: 50,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular nice shirt for every-one',
    },
    {
      name: 'fit shirt',
      slug: 'fit-shirt',
      category: 'shirts',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 8,
      countInStock: 13,
      description: 'A popular nice shirt for every-one',
    },
    {
      name: 'slim shirt',
      slug: 'slim-shirt',
      category: 'shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular nice shirt for every-one',
    },
    {
      name: 'golf pants',
      slug: 'golf-pant',
      category: 'pants',
      image: '/images/pants1.jpg',
      price: 110,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A smart looking pants',
    },
    {
      name: 'fit pants',
      slug: 'fit-pant',
      category: 'pants',
      image: '/images/pants2.jpg',
      price: 80,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants for every-one',
    },
    {
      name: 'classic pants',
      slug: 'classic-pant',
      category: 'pants',
      image: '/images/pants3.jpg',
      price: 120,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;
